// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.1
// source: oraclenode.proto

package iop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OracleNode_SendDeal_FullMethodName       = "/iop.OracleNode/SendDeal"
	OracleNode_Validate_FullMethodName       = "/iop.OracleNode/Validate"
	OracleNode_SequentialSign_FullMethodName = "/iop.OracleNode/SequentialSign"
)

// OracleNodeClient is the client API for OracleNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OracleNodeClient interface {
	SendDeal(ctx context.Context, in *SendDealRequest, opts ...grpc.CallOption) (*SendDealResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// ====== 新增：有序签名 RPC 接口 ======
	SequentialSign(ctx context.Context, in *SequentialSignRequest, opts ...grpc.CallOption) (*SequentialSignResponse, error)
}

type oracleNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewOracleNodeClient(cc grpc.ClientConnInterface) OracleNodeClient {
	return &oracleNodeClient{cc}
}

func (c *oracleNodeClient) SendDeal(ctx context.Context, in *SendDealRequest, opts ...grpc.CallOption) (*SendDealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDealResponse)
	err := c.cc.Invoke(ctx, OracleNode_SendDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oracleNodeClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, OracleNode_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oracleNodeClient) SequentialSign(ctx context.Context, in *SequentialSignRequest, opts ...grpc.CallOption) (*SequentialSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SequentialSignResponse)
	err := c.cc.Invoke(ctx, OracleNode_SequentialSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OracleNodeServer is the server API for OracleNode service.
// All implementations must embed UnimplementedOracleNodeServer
// for forward compatibility.
type OracleNodeServer interface {
	SendDeal(context.Context, *SendDealRequest) (*SendDealResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// ====== 新增：有序签名 RPC 接口 ======
	SequentialSign(context.Context, *SequentialSignRequest) (*SequentialSignResponse, error)
	mustEmbedUnimplementedOracleNodeServer()
}

// UnimplementedOracleNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOracleNodeServer struct{}

func (UnimplementedOracleNodeServer) SendDeal(context.Context, *SendDealRequest) (*SendDealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDeal not implemented")
}
func (UnimplementedOracleNodeServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedOracleNodeServer) SequentialSign(context.Context, *SequentialSignRequest) (*SequentialSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SequentialSign not implemented")
}
func (UnimplementedOracleNodeServer) mustEmbedUnimplementedOracleNodeServer() {}
func (UnimplementedOracleNodeServer) testEmbeddedByValue()                    {}

// UnsafeOracleNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OracleNodeServer will
// result in compilation errors.
type UnsafeOracleNodeServer interface {
	mustEmbedUnimplementedOracleNodeServer()
}

func RegisterOracleNodeServer(s grpc.ServiceRegistrar, srv OracleNodeServer) {
	// If the following call panics, it indicates UnimplementedOracleNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OracleNode_ServiceDesc, srv)
}

func _OracleNode_SendDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OracleNodeServer).SendDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OracleNode_SendDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OracleNodeServer).SendDeal(ctx, req.(*SendDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OracleNode_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OracleNodeServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OracleNode_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OracleNodeServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OracleNode_SequentialSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SequentialSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OracleNodeServer).SequentialSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OracleNode_SequentialSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OracleNodeServer).SequentialSign(ctx, req.(*SequentialSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OracleNode_ServiceDesc is the grpc.ServiceDesc for OracleNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OracleNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iop.OracleNode",
	HandlerType: (*OracleNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDeal",
			Handler:    _OracleNode_SendDeal_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _OracleNode_Validate_Handler,
		},
		{
			MethodName: "SequentialSign",
			Handler:    _OracleNode_SequentialSign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oraclenode.proto",
}
