// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: oraclenode.proto

package iop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest_Type int32

const (
	ValidateRequest_unknown     ValidateRequest_Type = 0
	ValidateRequest_block       ValidateRequest_Type = 1
	ValidateRequest_transaction ValidateRequest_Type = 2
)

// Enum value maps for ValidateRequest_Type.
var (
	ValidateRequest_Type_name = map[int32]string{
		0: "unknown",
		1: "block",
		2: "transaction",
	}
	ValidateRequest_Type_value = map[string]int32{
		"unknown":     0,
		"block":       1,
		"transaction": 2,
	}
)

func (x ValidateRequest_Type) Enum() *ValidateRequest_Type {
	p := new(ValidateRequest_Type)
	*p = x
	return p
}

func (x ValidateRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_oraclenode_proto_enumTypes[0].Descriptor()
}

func (ValidateRequest_Type) Type() protoreflect.EnumType {
	return &file_oraclenode_proto_enumTypes[0]
}

func (x ValidateRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateRequest_Type.Descriptor instead.
func (ValidateRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{2, 0}
}

type SendDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deal          *Deal                  `protobuf:"bytes,1,opt,name=deal,proto3" json:"deal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDealRequest) Reset() {
	*x = SendDealRequest{}
	mi := &file_oraclenode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDealRequest) ProtoMessage() {}

func (x *SendDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDealRequest.ProtoReflect.Descriptor instead.
func (*SendDealRequest) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{0}
}

func (x *SendDealRequest) GetDeal() *Deal {
	if x != nil {
		return x.Deal
	}
	return nil
}

type SendDealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDealResponse) Reset() {
	*x = SendDealResponse{}
	mi := &file_oraclenode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDealResponse) ProtoMessage() {}

func (x *SendDealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDealResponse.ProtoReflect.Descriptor instead.
func (*SendDealResponse) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{1}
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ValidateRequest_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=iop.ValidateRequest_Type" json:"type,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_oraclenode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequest) GetType() ValidateRequest_Type {
	if x != nil {
		return x.Type
	}
	return ValidateRequest_unknown
}

func (x *ValidateRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Deal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Deal          *EncryptedDeal         `protobuf:"bytes,2,opt,name=deal,proto3" json:"deal,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deal) Reset() {
	*x = Deal{}
	mi := &file_oraclenode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deal) ProtoMessage() {}

func (x *Deal) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deal.ProtoReflect.Descriptor instead.
func (*Deal) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{3}
}

func (x *Deal) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Deal) GetDeal() *EncryptedDeal {
	if x != nil {
		return x.Deal
	}
	return nil
}

func (x *Deal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EncryptedDeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DhKey         []byte                 `protobuf:"bytes,1,opt,name=dhKey,proto3" json:"dhKey,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Cipher        []byte                 `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedDeal) Reset() {
	*x = EncryptedDeal{}
	mi := &file_oraclenode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDeal) ProtoMessage() {}

func (x *EncryptedDeal) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDeal.ProtoReflect.Descriptor instead.
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptedDeal) GetDhKey() []byte {
	if x != nil {
		return x.DhKey
	}
	return nil
}

func (x *EncryptedDeal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EncryptedDeal) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedDeal) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	BlockNumber   int64                  `protobuf:"varint,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_oraclenode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ValidateResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ====== 新增：有序签名请求结构体 ======
type SequentialSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                 // 待签名的消息 (hash + result + type)
	PrevS         []byte                 `protobuf:"bytes,2,opt,name=prev_s,json=prevS,proto3" json:"prev_s,omitempty"`        // 上一个签名的 S 部分
	PrevR         []byte                 `protobuf:"bytes,3,opt,name=prev_r,json=prevR,proto3" json:"prev_r,omitempty"`        // 上一个签名的 R 部分
	IsFirst       bool                   `protobuf:"varint,4,opt,name=is_first,json=isFirst,proto3" json:"is_first,omitempty"` // 是否是第一个签名者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequentialSignRequest) Reset() {
	*x = SequentialSignRequest{}
	mi := &file_oraclenode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequentialSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequentialSignRequest) ProtoMessage() {}

func (x *SequentialSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequentialSignRequest.ProtoReflect.Descriptor instead.
func (*SequentialSignRequest) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{6}
}

func (x *SequentialSignRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SequentialSignRequest) GetPrevS() []byte {
	if x != nil {
		return x.PrevS
	}
	return nil
}

func (x *SequentialSignRequest) GetPrevR() []byte {
	if x != nil {
		return x.PrevR
	}
	return nil
}

func (x *SequentialSignRequest) GetIsFirst() bool {
	if x != nil {
		return x.IsFirst
	}
	return false
}

// ====== 新增：有序签名响应结构体 ======
type SequentialSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S             []byte                 `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"` // 当前签名的 S 部分
	R             []byte                 `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"` // 当前签名的 R 部分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequentialSignResponse) Reset() {
	*x = SequentialSignResponse{}
	mi := &file_oraclenode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequentialSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequentialSignResponse) ProtoMessage() {}

func (x *SequentialSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oraclenode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequentialSignResponse.ProtoReflect.Descriptor instead.
func (*SequentialSignResponse) Descriptor() ([]byte, []int) {
	return file_oraclenode_proto_rawDescGZIP(), []int{7}
}

func (x *SequentialSignResponse) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *SequentialSignResponse) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

var File_oraclenode_proto protoreflect.FileDescriptor

const file_oraclenode_proto_rawDesc = "" +
	"\n" +
	"\x10oraclenode.proto\x12\x03iop\"0\n" +
	"\x0fSendDealRequest\x12\x1d\n" +
	"\x04deal\x18\x01 \x01(\v2\t.iop.DealR\x04deal\"\x12\n" +
	"\x10SendDealResponse\"\x85\x01\n" +
	"\x0fValidateRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.iop.ValidateRequest.TypeR\x04type\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"/\n" +
	"\x04Type\x12\v\n" +
	"\aunknown\x10\x00\x12\t\n" +
	"\x05block\x10\x01\x12\x0f\n" +
	"\vtransaction\x10\x02\"b\n" +
	"\x04Deal\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12&\n" +
	"\x04deal\x18\x02 \x01(\v2\x12.iop.EncryptedDealR\x04deal\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"q\n" +
	"\rEncryptedDeal\x12\x14\n" +
	"\x05dhKey\x18\x01 \x01(\fR\x05dhKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x16\n" +
	"\x06cipher\x18\x04 \x01(\fR\x06cipher\"|\n" +
	"\x10ValidateResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12 \n" +
	"\vblockNumber\x18\x03 \x01(\x03R\vblockNumber\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"z\n" +
	"\x15SequentialSignRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\x12\x15\n" +
	"\x06prev_s\x18\x02 \x01(\fR\x05prevS\x12\x15\n" +
	"\x06prev_r\x18\x03 \x01(\fR\x05prevR\x12\x19\n" +
	"\bis_first\x18\x04 \x01(\bR\aisFirst\"4\n" +
	"\x16SequentialSignResponse\x12\f\n" +
	"\x01s\x18\x01 \x01(\fR\x01s\x12\f\n" +
	"\x01r\x18\x02 \x01(\fR\x01r2\xc9\x01\n" +
	"\n" +
	"OracleNode\x127\n" +
	"\bSendDeal\x12\x14.iop.SendDealRequest\x1a\x15.iop.SendDealResponse\x127\n" +
	"\bValidate\x12\x14.iop.ValidateRequest\x1a\x15.iop.ValidateResponse\x12I\n" +
	"\x0eSequentialSign\x12\x1a.iop.SequentialSignRequest\x1a\x1b.iop.SequentialSignResponseB\aZ\x05.;iopb\x06proto3"

var (
	file_oraclenode_proto_rawDescOnce sync.Once
	file_oraclenode_proto_rawDescData []byte
)

func file_oraclenode_proto_rawDescGZIP() []byte {
	file_oraclenode_proto_rawDescOnce.Do(func() {
		file_oraclenode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oraclenode_proto_rawDesc), len(file_oraclenode_proto_rawDesc)))
	})
	return file_oraclenode_proto_rawDescData
}

var file_oraclenode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oraclenode_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_oraclenode_proto_goTypes = []any{
	(ValidateRequest_Type)(0),      // 0: iop.ValidateRequest.Type
	(*SendDealRequest)(nil),        // 1: iop.SendDealRequest
	(*SendDealResponse)(nil),       // 2: iop.SendDealResponse
	(*ValidateRequest)(nil),        // 3: iop.ValidateRequest
	(*Deal)(nil),                   // 4: iop.Deal
	(*EncryptedDeal)(nil),          // 5: iop.EncryptedDeal
	(*ValidateResponse)(nil),       // 6: iop.ValidateResponse
	(*SequentialSignRequest)(nil),  // 7: iop.SequentialSignRequest
	(*SequentialSignResponse)(nil), // 8: iop.SequentialSignResponse
}
var file_oraclenode_proto_depIdxs = []int32{
	4, // 0: iop.SendDealRequest.deal:type_name -> iop.Deal
	0, // 1: iop.ValidateRequest.type:type_name -> iop.ValidateRequest.Type
	5, // 2: iop.Deal.deal:type_name -> iop.EncryptedDeal
	1, // 3: iop.OracleNode.SendDeal:input_type -> iop.SendDealRequest
	3, // 4: iop.OracleNode.Validate:input_type -> iop.ValidateRequest
	7, // 5: iop.OracleNode.SequentialSign:input_type -> iop.SequentialSignRequest
	2, // 6: iop.OracleNode.SendDeal:output_type -> iop.SendDealResponse
	6, // 7: iop.OracleNode.Validate:output_type -> iop.ValidateResponse
	8, // 8: iop.OracleNode.SequentialSign:output_type -> iop.SequentialSignResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_oraclenode_proto_init() }
func file_oraclenode_proto_init() {
	if File_oraclenode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oraclenode_proto_rawDesc), len(file_oraclenode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oraclenode_proto_goTypes,
		DependencyIndexes: file_oraclenode_proto_depIdxs,
		EnumInfos:         file_oraclenode_proto_enumTypes,
		MessageInfos:      file_oraclenode_proto_msgTypes,
	}.Build()
	File_oraclenode_proto = out.File
	file_oraclenode_proto_goTypes = nil
	file_oraclenode_proto_depIdxs = nil
}
